const referenceAssetBase = '/rtc-reference-assets'

export function referenceAsset(number) {
  return `${referenceAssetBase}/asset-(${number}).png`
}

export const feedTabs = [
  { value: 'following', label: 'Following', mobileLabel: 'Mine', filter: 'all' },
  { value: 'for_you', label: 'For You', mobileLabel: 'Popular', filter: 'all' },
  { value: 'explore', label: 'Explore', filter: 'all' },
  { value: 'party', label: 'Party', filter: 'pk' },
  { value: 'nearby', label: 'Nearby', filter: 'all' },
  { value: 'latest', label: 'Latest', filter: 'all', sort: 'newest' },
  { value: 'global', label: 'Global', filter: 'all' },
]

export const exploreFilters = [
  { value: 'all', label: 'All', filter: 'all' },
  { value: 'new_host', label: 'New Host', filter: 'live' },
  { value: 'games', label: 'Games', filter: 'video' },
  { value: 'pk', label: 'PK', filter: 'pk' },
]

export const demoCards = [
  { id: 'demo-1', title: 'Creator Studio Warm-up', host: 'Maya Studio', viewers: 5631, tone: 'aurora', country: 'United States', size: 'feature', badge: 'Group Video', roomType: 'group_video', avatarIndex: 0 },
  { id: 'demo-2', title: 'Open Mic Lounge', host: 'Luna Waves', viewers: 6018, tone: 'warm', category: 'Music', badge: 'Music', roomType: 'audio', avatarIndex: 1 },
  { id: 'demo-3', title: 'Daily Product Standup', host: 'Nora Labs', viewers: 1794, tone: 'rose', category: 'Video', roomType: 'video', avatarIndex: 2 },
  { id: 'demo-4', title: 'Design Review Live', host: 'Pixel Team', viewers: 6186, tone: 'sunset', roomType: 'group_video', avatarIndex: 3 },
  { id: 'demo-5', title: 'Creator Office Hours', host: 'TalkEachOther', viewers: 1090, tone: 'slate', roomType: 'solo_live', avatarIndex: 4 },
  { id: 'demo-6', title: 'Acoustic Session', host: 'Matt M.', viewers: 589, tone: 'amber', roomType: 'group_audio', avatarIndex: 5 },
  { id: 'demo-7', title: 'Night Studio', host: 'Natalie', viewers: 5689, tone: 'night', roomType: 'video', avatarIndex: 6 },
  { id: 'demo-8', title: 'Global Music Room', host: 'Lyss', viewers: 1418, tone: 'plum', country: 'Canada', roomType: 'audio', avatarIndex: 7 },
  { id: 'demo-9', title: 'Supporter Lounge', host: 'Community Ops', viewers: 2032, tone: 'copper', badge: 'Community', roomType: 'group_audio', avatarIndex: 1 },
  { id: 'demo-10', title: 'Morning Sync', host: 'Sarah', viewers: 7489, tone: 'cloud', roomType: 'group_video', avatarIndex: 2 },
  { id: 'demo-11', title: 'Private Client Demo', host: 'Enterprise Desk', viewers: 1853, tone: 'wine', privacy: 'private', badge: 'Private', roomType: 'video', avatarIndex: 3 },
  { id: 'demo-12', title: 'Password Beta Room', host: 'QA Studio', viewers: 928, tone: 'silver', privacy: 'password', badge: 'Locked', roomType: 'video', avatarIndex: 4 },
  { id: 'demo-13', title: 'Fresh Creator Drop', host: 'Winnie', viewers: 208, tone: 'olive', tab: 'latest', roomType: 'solo_live', avatarIndex: 5 },
  { id: 'demo-14', title: 'New Host Practice', host: 'Seyi', viewers: 84, tone: 'taupe', tab: 'latest', roomType: 'video', avatarIndex: 6 },
  { id: 'demo-15', title: 'Audio Check Room', host: 'Engineering', viewers: 77, tone: 'mono', tab: 'latest', roomType: 'audio', avatarIndex: 7 },
  { id: 'demo-16', title: 'First Stream Setup', host: 'Vee Studio', viewers: 136, tone: 'rose', tab: 'latest', roomType: 'solo_live', avatarIndex: 0 },
  { id: 'demo-17', title: 'Nearby Creators', host: 'John F.', viewers: 527, tone: 'earth', tab: 'nearby', roomType: 'group_video', avatarIndex: 1 },
  { id: 'demo-18', title: 'Community Check-in', host: 'Art Room', viewers: 181, tone: 'mid', tab: 'nearby', roomType: 'group_audio', avatarIndex: 2 },
  { id: 'demo-19', title: 'Moderator Training', host: 'Ocean Ops', viewers: 57, tone: 'violet', tab: 'nearby', roomType: 'video', avatarIndex: 3 },
  { id: 'demo-20', title: 'Local Music Circle', host: 'ChiChi', viewers: 1238, tone: 'pink', tab: 'nearby', roomType: 'audio', avatarIndex: 4 },
  { id: 'demo-21', title: 'Game Night Voice', host: 'Paniax Gaming', viewers: 299, tone: 'game', tab: 'explore', explore: 'games', roomType: 'group_video', avatarIndex: 5 },
  { id: 'demo-22', title: 'Watch Party Studio', host: 'Cleo', viewers: 1230, tone: 'sand', tab: 'explore', explore: 'games', roomType: 'group_video', avatarIndex: 6 },
  { id: 'demo-23', title: 'Film Room Live', host: 'Prime Stage', viewers: 68279, tone: 'ocean', tab: 'explore', explore: 'games', roomType: 'video', avatarIndex: 7 },
  { id: 'demo-24', title: 'PK Creator Battle', host: 'United States', viewers: 865, tone: 'sky', tab: 'party', party: true, roomType: 'pk_live', avatarIndex: 0 },
  { id: 'demo-25', title: 'Community Party', host: 'Stage Hosts', viewers: 5133, tone: 'storm', tab: 'party', party: true, roomType: 'group_video', avatarIndex: 1 },
  { id: 'demo-26', title: 'Cozy Streamer Night', host: 'The Cozy Studio', viewers: 244, tone: 'ember', tab: 'party', party: true, roomType: 'solo_live', avatarIndex: 2 },
  { id: 'demo-27', title: 'Community Guidelines Preview', host: 'Trust and Safety', viewers: 6345, tone: 'sensitive', sensitive: true, privacy: 'private', roomType: 'video', avatarIndex: 3 },
]

export const defaultClientCompanies = [
  { id: 'client-accenture', name: 'Accenture', detail: 'Enterprise RTC client', roomCount: 0, avatarIndex: 2 },
  { id: 'client-imo', name: 'IMO', detail: 'Video rooms client', roomCount: 0, avatarIndex: 6 },
]

export const dmThreads = [
  { id: 'donna', peerId: 32165333, name: 'Donna Walk3...', time: 'Wednesday 19:24', preview: 'Hi, are you joining the live room today?', unread: 1, followed: false },
  { id: 'jennifer', peerId: 32165334, name: 'Jennifer Ortiz...', time: 'Wednesday 17:35', preview: 'Can you check the room invite I sent?', unread: 1, followed: false },
  { id: 'friend', peerId: 32165335, name: 'Friend...', time: 'Wednesday 01:27', preview: 'Following up on the private room link.', unread: 4, followed: true },
  { id: 'buzz', peerId: 32165336, name: 'TalkEachOther', time: 'Wednesday 01:27', preview: 'Welcome to the TalkEachOther lobby.', unread: 1, followed: true },
]

export const initialDmMessages = {
  donna: [{ id: 'donna-1', author: 'Donna Walk3...', body: 'Hi, are you joining the live room today?', mine: false }],
  jennifer: [{ id: 'jennifer-1', author: 'Jennifer Ortiz...', body: 'Can you check the room invite I sent?', mine: false }],
  friend: [
    { id: 'friend-1', author: 'Friend...', body: 'Following up on the private room link.', mine: false },
    { id: 'friend-2', author: 'You', body: 'Yes, send it again and I will join.', mine: true },
  ],
  buzz: [{ id: 'welcome', author: 'TalkEachOther', body: 'Welcome to the TalkEachOther lobby.', mine: false }],
}

export const settingsNav = [
  { value: 'account', labelKey: 'Account Security', icon: 'U' },
  { value: 'privacy', labelKey: 'Privacy Settings', icon: 'S' },
  { value: 'content', labelKey: 'Content Preferences', icon: 'F' },
  { value: 'region', labelKey: 'Region', icon: 'P' },
  { value: 'terms', labelKey: 'Terms and Policies', icon: 'D' },
]

export const settingsCopy = {
  'Account Security': 'Account Security',
  'Privacy Settings': 'Privacy Settings',
  'Content Preferences': 'Content Preferences',
  Region: 'Region',
  'Terms and Policies': 'Terms and Policies',
  'Changes are applied immediately for this session.': 'Changes are applied immediately for this session.',
  'Binding cell phone': 'Binding cell phone',
  'Recommended for account recovery and high-value payments.': 'Recommended for account recovery and high-value payments.',
  'Binding email': 'Binding email',
  'Used for login recovery and security notices.': 'Used for login recovery and security notices.',
  'Set login password': 'Set login password',
  'Protect this account when signing in on a new device.': 'Protect this account when signing in on a new device.',
  'Devices Logged In': 'Devices Logged In',
  'Show alerts when a new device logs in.': 'Show alerts when a new device logs in.',
  Bound: 'Bound',
  Set: 'Set',
  'Bind cell phone': 'Bind cell phone',
  'Bind email': 'Bind email',
  'Set password': 'Set password',
  'Alerts on': 'Alerts on',
  'Alerts off': 'Alerts off',
  'Cell phone bound.': 'Cell phone bound.',
  'Email bound.': 'Email bound.',
  'Login password set.': 'Login password set.',
  'Device login alerts updated.': 'Device login alerts updated.',
  Cancel: 'Cancel',
  Save: 'Save',
  'Cell phone number': 'Cell phone number',
  'Email address': 'Email address',
  'New password': 'New password',
  'Confirm password': 'Confirm password',
  'Enter a valid phone number.': 'Enter a valid phone number.',
  'Enter a valid email address.': 'Enter a valid email address.',
  'Use at least 10 characters for the password.': 'Use at least 10 characters for the password.',
  'Passwords do not match.': 'Passwords do not match.',
  'Who can send me a message': 'Who can send me a message',
  'Controls the personal inbox and room chat shortcuts.': 'Controls the personal inbox and room chat shortcuts.',
  Everyone: 'Everyone',
  'Followers only': 'Followers only',
  Nobody: 'Nobody',
  'Private live invitation': 'Private live invitation',
  'Allow hosts to invite you into private live rooms.': 'Allow hosts to invite you into private live rooms.',
  Blacklist: 'Blacklist',
  'Blocked users are controlled from the chat user menu.': 'Blocked users are controlled from the chat user menu.',
  'Live broadcast you are not interested in': 'Live broadcast you are not interested in',
  'Filtered from your feed.': 'Filtered from your feed.',
  'Visible in your feed.': 'Visible in your feed.',
  Filtered: 'Filtered',
  Show: 'Show',
  'Message privacy updated.': 'Message privacy updated.',
  'Private live invitation setting updated.': 'Private live invitation setting updated.',
  'Live preference updated.': 'Live preference updated.',
  'Restricted Mode': 'Restricted Mode',
  'Hide potentially sensitive content.': 'Hide potentially sensitive content.',
  'Warning Mode': 'Warning Mode',
  'Show a warning before sensitive rooms open.': 'Show a warning before sensitive rooms open.',
  'All Modes': 'All Modes',
  'Show all room content that is available to your account.': 'Show all room content that is available to your account.',
  'selected.': 'selected.',
  'Search region': 'Search region',
  'Region changed to {region}.': 'Region changed to {region}.',
  'Terms of Service': 'Terms of Service',
  'Privacy Policy': 'Privacy Policy',
  'Child Safety Policy': 'Child Safety Policy',
  'Anti-Bullying Policy': 'Anti-Bullying Policy',
  Copyright: 'Copyright',
  '{policy} will open in the production policy page.': '{policy} will open in the production policy page.',
}
export const regions = [
  'Afghanistan',
  'Aland Islands',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bonaire, Sint Eustatius and Saba',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos Islands',
  'Colombia',
  'Comoros',
  'Congo',
  'Congo, Democratic Republic of the',
  'Cook Islands',
  'Costa Rica',
  "Cote d'Ivoire",
  'Croatia',
  'Cuba',
  'Curacao',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Falkland Islands',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and McDonald Islands',
  'Holy See',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'North Korea',
  'North Macedonia',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Reunion',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Barthelemy',
  'Saint Helena, Ascension and Tristan da Cunha',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia and the South Sandwich Islands',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'United States Minor Outlying Islands',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Virgin Islands, British',
  'Virgin Islands, U.S.',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe',
]
export const regionAliases = {
  'Cote d\'Ivoire': ['Ivory Coast'],
  'Czechia': ['Czech Republic'],
  'Congo': ['Republic of the Congo'],
  'Congo, Democratic Republic of the': ['DR Congo', 'Democratic Republic of Congo'],
  'Eswatini': ['Swaziland'],
  'Holy See': ['Vatican City', 'Vatican'],
  'Iran': ['Islamic Republic of Iran'],
  'Laos': ['Lao PDR'],
  'Macao': ['Macau'],
  'Myanmar': ['Burma'],
  'North Korea': ['Korea DPR'],
  'Palestine': ['Palestinian Territory'],
  'Russia': ['Russian Federation'],
  'South Korea': ['Korea', 'Republic of Korea'],
  'Syria': ['Syrian Arab Republic'],
  'Taiwan': ['Taiwan, Province of China'],
  'Tanzania': ['United Republic of Tanzania'],
  'Turkey': ['Turkiye'],
  'United Arab Emirates': ['UAE'],
  'United Kingdom': ['UK', 'Great Britain', 'Britain', 'England', 'Scotland', 'Wales', 'Northern Ireland'],
  'United States': ['USA', 'US', 'United States of America', 'America'],
  'Venezuela': ['Bolivarian Republic of Venezuela'],
  'Vietnam': ['Viet Nam'],
}
export const feedbackCategories = ['Account', 'Room / RTC', 'Chat', 'Safety', 'Other']
export const feedbackTypes = ['Bug report', 'Feature request', 'Access issue', 'Abuse report', 'Other']
export const maxFeedbackAttachmentSize = 25 * 1024 * 1024

export const popularHelp = [
  { id: 'create-room', title: 'How to create a room', body: 'Open the create room panel, choose the room type and privacy, then publish the room when the details are ready.' },
  { id: 'vip', title: 'How to become VIP/SVIP', body: 'Open the personal center to review available VIP access, rewards, and account privileges.' },
  { id: 'bind', title: 'How do I bind my phone number and email address?', body: 'For account security, bind your mobile phone number and email address in Settings, Account Security.' },
  { id: 'mvp', title: 'How to become an MVP and its benefits', body: 'MVP status unlocks monthly rewards, profile progress, and room benefits after qualifying top-up milestones.' },
  { id: 'missing', title: 'I submitted feedback but need help', body: 'Open Feedback record to review previous reports, or submit a new ticket with screenshots and device details.' },
]

export const faqTopics = [
  'Modify personal information',
  'Unfollow accounts that are frozen or deactivated',
  'How to create a voice chat room',
  'How do I bind my phone number and email address?',
  'How to upgrade the TalkEachOther app',
  "Delete the other people's comments on your post or private message with others",
  'The live streaming page cannot be opened or is not smooth',
  'How to do a live/private live broadcast',
  'Block others',
  'How to upgrade my account level',
  "Join other people's private broadcast",
  'Hide profile',
  'Turn off my location',
  'Delete video',
]
export const faqAnswers = {
  'Modify personal information': 'Open your profile, edit the fields you want to change, then save. Some account security fields are managed from Settings.',
  'Unfollow accounts that are frozen or deactivated': 'Open the account page from your following list and use Unfollow. Frozen or deactivated accounts may take a short time to disappear from lists.',
  'How to create a voice chat room': 'Use the create room panel, choose an audio room type, complete the room details, and create the room.',
  'How do I bind my phone number and email address?': 'Go to Settings, Account Security, then use Binding cell phone or Binding email.',
  'How to upgrade the TalkEachOther app': 'Refresh the web app or install the latest app version from your browser install prompt when it is available.',
  "Delete the other people's comments on your post or private message with others": 'Use the message or comment menu. Room owners and moderators can remove disruptive room messages.',
  'The live streaming page cannot be opened or is not smooth': 'Check your network, close other heavy apps, refresh the room, and try a different room. If it continues, submit feedback with your device and network details.',
  'How to do a live/private live broadcast': 'Create a room, choose a live room type, then select public, private, or password privacy before publishing.',
  'Block others': 'Open the user menu from chat, profile, or room participants, then choose block or report when needed.',
  'How to upgrade my account level': 'Account level grows through activity, room participation, and supported platform reward actions.',
  "Join other people's private broadcast": 'Open the private room invitation or room card. If a password or permission is required, enter it before joining.',
  'Hide profile': 'Use privacy settings to limit who can message you and reduce discoverability where supported.',
  'Turn off my location': 'Disable browser location permission and choose a different region from Settings if needed.',
  'Delete video': 'Open your video or room media controls and choose delete. Moderation tools may also remove unsafe videos.',
}

export const policyDocuments = [
  {
    id: 'terms',
    title: 'Terms of Service',
    summary: 'The basic rules for using TalkEachOther rooms, chat, profiles, and RTC features.',
    sections: [
      ['Account responsibility', 'You are responsible for activity from your account, keeping your login details private, and using accurate profile information.'],
      ['Room behavior', 'Do not harass people, impersonate others, share illegal content, or use live rooms for scams, private transactions, or harmful activity.'],
      ['Service changes', 'Features, rooms, moderation tools, and availability may change as the service improves or to protect the community.'],
    ],
  },
  {
    id: 'privacy',
    title: 'Privacy Policy',
    summary: 'How account, room, chat, device, and usage information is handled inside the platform.',
    sections: [
      ['Information we use', 'We use account details, room activity, messages, device signals, and usage records to run the service and keep rooms safe.'],
      ['Security and moderation', 'Safety teams and automated systems may review reports, moderation events, and abuse signals to protect users.'],
      ['Your choices', 'You can update profile details, manage privacy settings, and control room or message preferences from settings.'],
    ],
  },
  {
    id: 'child-safety',
    title: 'Child Safety Policy',
    summary: 'Rules that protect minors and remove unsafe content or behavior quickly.',
    sections: [
      ['Minimum age', 'Users must meet the required age for their region. Accounts that do not meet age requirements may be restricted or removed.'],
      ['Zero tolerance', 'Sexualized, exploitative, grooming, or predatory behavior involving minors is prohibited and may be reported to authorities.'],
      ['Reporting', 'Use Feedback and Help or moderation controls to report suspicious behavior, unsafe rooms, or child safety concerns immediately.'],
    ],
  },
  {
    id: 'anti-bullying',
    title: 'Anti-Bullying Policy',
    summary: 'Community rules for respectful live rooms, chat, direct messages, and profiles.',
    sections: [
      ['Harassment', 'Threats, targeted insults, hate speech, stalking, doxxing, and repeated unwanted contact are not allowed.'],
      ['Moderation tools', 'Room owners and moderators can mute, remove, block, or report users who disrupt rooms or attack others.'],
      ['Enforcement', 'Violations may lead to removed content, disabled rooms, account restrictions, or bans.'],
    ],
  },
  {
    id: 'copyright',
    title: 'Copyright',
    summary: 'Rules for sharing music, images, video, branding, and other protected content.',
    sections: [
      ['Your content', 'Only upload or stream content you own, created, licensed, or have permission to use.'],
      ['Claims', 'Copyright owners can report content that they believe infringes their rights. Valid reports may result in removal or account action.'],
      ['Repeat violations', 'Repeated copyright abuse can lead to room restrictions or account suspension.'],
    ],
  },
]
